sudo: false

language: python

python:
  - 3.6

#install dependencies
install: pip install -r requirements.txt

before_script: python main.py

# command to install dependencies
script: python tests.py

branches:
  only:
    - master